package com.example.luca.planit;

/**
 * Created by diego on 22/07/2017.
 */

public enum RequestResult {
    OK_LOGIN,
    WRONG_PASSWORD,
    USERNAME_ALREADY_EXISTING,
    MAIL_ALREADY_PRESENT,
    OK_REGISTRATION,
    MAIL_NOT_PRESENT,
    NOT_EXISTING_MAIL,
    NOT_EXISTING_USERNAME,
    INVITE_SENDED,
    INVITE_UPDATED,
    TASK_ASSIGNED,
    USERNAME_NOT_PRESENT,
    GROUP_CREATED, EVENT_DELETED,
    INSERTED_TIME_PREFERENCE,
    INSERTED_DATA_PREFERENCE,
    INSERTED_PLACE_PREFERENCE,
    NO_CONNECTION,
    OK_UPDATE;
}
